version: '3.8'

services:
  postgres:
    build: ./database
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - aahar-db-volume:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    

volumes:
  aahar-db-volume: